'use strict';


angular.module('app', [
    'ngAnimate',
    'ngAria',
    'ngCookies',
    'ngMessages',
    'ngResource',
    'ngSanitize',
    'ngTouch',
    'ngStorage',
    'ui.router',
    'ui.bootstrap',
    'ui.utils',
    'ui.load',
    'ui.jq',
    'oc.lazyLoad',
    'angularMoment',
    'ngFileUpload',
    'ngMap',
    'toaster',
    'bootstrapLightbox',
    'angularUtils.directives.dirPagination',
    'cp.ngConfirm',
    'angular-button-spinner',
    'ismobile',
    'ui.calendar',
    'slickCarousel',
    'ngScrollbars',
    'firebase',
    'anguvideo',
    'vkEmojiPicker',
    'videosharing-embed'
]);
